import { marked } from 'marked';

/**
 * Renders the tool-delivery emails from their markdown templates in
 * `src/lib/emails/tool-*.md`.
 *
 * The numbered files in that folder (`00.md`–`03.md`) are NOT sent by anything
 * here: they are Damian's drafts for Substack posts (00 is the welcome email he
 * should paste into Substack's own settings). The sending machinery they once
 * had — /api/subscribe, the daily sequence — was removed in August 2026 as
 * unused; git history has it if the iframe ever goes.
 */
function parse(raw: string): { subject: string; preheader: string; body: string } {
	let body = raw;
	let subject = '';
	let preheader = '';
	const frontmatter = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
	if (frontmatter) {
		body = raw.slice(frontmatter[0].length);
		for (const line of frontmatter[1].split('\n')) {
			const trimmed = line.trim();
			if (!trimmed || trimmed.startsWith('#')) continue;
			const separator = trimmed.indexOf(':');
			if (separator === -1) continue;
			const key = trimmed.slice(0, separator).trim();
			if (key === 'subject') subject = trimmed.slice(separator + 1).trim();
			if (key === 'preheader') preheader = trimmed.slice(separator + 1).trim();
		}
	}
	return { subject, preheader, body };
}

function shell(inner: string, unsubscribeUrl: string, preheader = ''): string {
	// The preheader is the line inbox clients show after the subject. It is
	// painted invisible inside the body; the trailing no-width characters keep
	// clients from filling the preview with the email's first real sentence.
	const preview = preheader
		? `<div style="display:none;max-height:0;overflow:hidden;mso-hide:all;">${preheader}${'&nbsp;&zwnj;'.repeat(20)}</div>`
		: '';
	return `<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
/*
 * The minimum that can't go inline, because the HTML is generated by marked
 * from the markdown and never passes through here.
 *
 * Gmail honours a <style> in the <head>; clients that don't keep default
 * indentation and sizing, which still read fine. So this improves where it can
 * and breaks nothing where it can't.
 *
 * The blockquotes are the report previews from /tool/newsletter: what whoever
 * shares your link sees, what shows in the inbox and what shows on Google.
 * With a border they read as what they are — a card — not as indented text.
 */
blockquote{margin:12px 0;padding:12px 16px;border:1px solid #e5e5e5;border-radius:8px;background:#fafafa;}
blockquote p{margin:0;}
h1{font-size:32px;line-height:1.1;margin:0 0 8px;}
h2{font-size:20px;line-height:1.3;margin:32px 0 8px;}
hr{border:none;border-top:1px solid #e5e5e5;margin:32px 0;}
a{color:#0076ff;}
</style>
</head>
<body style="margin:0;background:#f7f6f2;">
${preview}
<div style="max-width:34rem;margin:0 auto;padding:32px 20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#171717;">
<div style="background:#ffffff;border:1px solid #e5e5e5;border-radius:12px;padding:28px 24px;">
${inner}
</div>
<p style="font-size:12px;color:#737373;margin:16px 4px 0;">
Recibes esto porque dejaste tu email en mi web.
<a href="${unsubscribeUrl}" style="color:#737373;">Darte de baja</a> en un clic.
</p>
</div>
</body>
</html>`;
}

/**
 * Render a one-off email from raw markdown with frontmatter. Used by the tools
 * to deliver their generated output.
 */
export function renderStandalone(
	raw: string,
	unsubscribeUrl: string,
	vars: Record<string, string> = {}
): { subject: string; html: string } {
	const { subject, preheader, body } = parse(raw);

	// Substitution happens AFTER splitting the frontmatter, and only on the
	// body. Done earlier, a `{{...}}` mentioned in a frontmatter comment takes
	// the content with it, and since that content carries `---` separators it
	// cuts the frontmatter in half: the email goes out with no subject and a
	// scrambled body. It really happened.
	let filled = body;
	for (const [key, value] of Object.entries(vars)) {
		filled = filled.split(`{{${key}}}`).join(value);
	}

	if (!subject) throw new Error('El correo no tiene subject en su frontmatter');

	return { subject, html: shell(marked.parse(filled) as string, unsubscribeUrl, preheader) };
}
